### ISSUE TITLE
Mozilla Curriculum Workshop  - Assets Needed

### ISSUE THREAD

**Issue by emmairwin** [mozilla/community-teaching-training#1]
For the Mozilla Curriculum Workshop (https://teach.mozilla.org/community/curriculum-workshop/), we would like
1. A title card/slide.
2. A card with our URL.
3. An update-able credits card.
4. A short (10 second? 30 second?) piece of music we can play part of at the start and end of the show and that we can loop, if needed, during workshopping time as people fall quiet and hack on prototypes. Maybe something with a techno-futurist-world-beat feel.

**Comment by emmairwin** [comment]
Card =  A slide or tile or graphic :)

**Comment by verenanz1** [comment]
Emma- so I am trying to translate this action item.

I think that you're are asking for  a ppt like slide with an image (assuming CC license) and some cool music. The slide has to be able to be updated. 

Could I do this in Google slides so it would have a link?

Which url would I use? The one to the curriculum workshop?

These questions may sound simple, but I am wondering what kinds of tools I can use. I know that Google is scary because of data/privacy, but I don't know of many open source tools that I could use....?

Verena :)

**Comment by emmairwin** [comment]
These are not simple questions at all - but clarifying questions .  Thanks Verena.

Pinging @chadsansing for clarification or examples of similar

**Comment by chadsansing** [comment]
I am on PTO, so let me throw this over to our production & comms team, @poh & @kgorr.

**Comment by emmairwin** [comment]
Chad had said 'slide', and we work with Google docs all the time.  So that hopefully answers that question.

**Comment by verenanz1** [comment]
Great - that is doable! :)

On Mon, Mar 28, 2016 at 11:24 AM, Emma notifications@github.com wrote:

> Chad had said 'slide', and we work with Google docs all the time. So that
> hopefully answers that question.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/community-teaching-training/issues/1#issuecomment-202495387

## 

Verena Roberts BEd, MALT, MET, EdD (_In progress_)​

eLearning Consultant and Innovator

email: verenanz@gmail.com

twitter: @verenanz

​(403) 612-2454​

**Comment by KGorr** [comment]
I believe Google slides should be adequate. Thank you!

**Comment by jsan4christ** [comment]
And this is for everybody and any body todo?

What message should be conveyed here? by the picture and music?

**Comment by emmairwin** [comment]
we will tiriage tasks on wednessday, but will assign to verena until then
to avoid duplicate work

On Mon, Mar 28, 2016 at 9:33 PM, San Emmanuel James <
notifications@github.com> wrote:

> And this is for everybody and any body todo?
> 
> What message should be conveyed here? by the picture and music?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/community-teaching-training/issues/1#issuecomment-202704256

## 

Emma Irwin
@sunnydeveloper
Mozilla Reps Mentor

**Comment by verenanz1** [comment]
Looking forward to completing this assignment.

Any amazing community images could be forwarded or attached to this thread? Or is there a place we could add them? @emma could we suggest picking a common area for collecting our community's digital resources?

**Comment by emmairwin** [comment]
@verenanz1 I often use Flickr (CC search #mozilla )

**Comment by verenanz1** [comment]
Hello - I have 2 possible music files ready...CC licensed of course, but I couldn't figure out how to attach them to this post....I also couldn't figure out how to add them to a google slide presentation.

I thought I could create youtube videos, then link those in, but that seemed awful complicated.

So - here is the link to the slide presentation:
[https://docs.google.com/presentation/d/1xPvheJSKyzAQyqwUCl8ncqO5vFoPK57HtPEVR0h4rWM/edit#slide=id.p](https://docs.google.com/presentation/d/1xPvheJSKyzAQyqwUCl8ncqO5vFoPK57HtPEVR0h4rWM/edit#slide=id.p)

I am missing the correct url to add in, because I don't know which one to add in.

Here are the links to the two music suggestions. As i mentioned, I have downloaded them, but don;t know how to add them here?
[https://www.jamendo.com/search?q=Electronic%20dance](https://www.jamendo.com/search?q=Electronic%20dance)

The ones I like are: Electron Dance (Arnaud Tranquil) & Electric Dancer (Koni)

So - based on this mini activity, we are going to need a quick "What is a CC LIcence and How to find CC Content" lesson/workshop.

I already pulled together some resources for a workshop that I did with Rhonda Jessen.
[https://docs.google.com/document/d/1hWJeGRP7fSmTyZ2MTL0Q_PDHkansA2TELrKFCSuLV70/edit](https://docs.google.com/document/d/1hWJeGRP7fSmTyZ2MTL0Q_PDHkansA2TELrKFCSuLV70/edit)

Ok - That's all I have .....

Verena :)

**Comment by chadsansing** [comment]
Hey, @verenanz1 - nice to catch up with you here. I really dig the Electron Dance - @ohnopauloh, @KGorr, @amirad, what do you think of 1:57 - 2:10 as intro/closing music?

I'd like to play around with the graphic some and see what happens when we color shift it. Will shareback. Others should chime in and play around.

**Comment by chadsansing** [comment]
Struggling to find a place and color scheme that works with a MCW title, e.g.

![screen shot 2016-04-04 at 7 23 42 am](https://cloud.githubusercontent.com/assets/4128600/14246611/517ab868-fa36-11e5-8642-de208ebf0df7.png)

Suggestions? Alternative backdrops? Grabbed the font from[ this Thimble project](https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/17695/) and screen-capped it.

**Comment by emmairwin** [comment]
The design community can likely consult here, so created a ticket

https://github.com/mozilla/Community-Design/issues/55

**Comment by verenanz1** [comment]
For the music- I searched for "energy- dance- motivational" but then I chose ones that weren't too techy

For the image- I was going for everyone in the international community has a voice and a chance to lend a hand/ support

**Comment by chadsansing** [comment]
@verenanz1, I thought the ideas were spot on -

**Comment by verenanz1** [comment]
Thanks @chadsansing  that means a lot coming from the idea king :) no joke!

**Comment by chadsansing** [comment]
We are all #onemozilla. Also, idea jester, please ;)

**Comment by chadsansing** [comment]
How about this, inspired by @verenanz1's idea:

![mcw-title-slide](https://cloud.githubusercontent.com/assets/4128600/14393312/42d6598c-fd94-11e5-83d3-8d265190574b.png)

cc @ohnopauloh, @KGorr, @amirad, @emmairwin, @ldecoursy

**Comment by KGorr** [comment]
Oooo! I like this one!

**Comment by ldecoursy** [comment]
We should also probably make sure this follows MLN style guidelines cc @hannahkane @xmatthewx

**Comment by ldecoursy** [comment]
Also just noticed it's missing a "c" in curriculum :)

**Comment by chadsansing** [comment]
Thanks, @ldecoursy - tried to make it flat; used the font from the clubs word mark Thimble project, and pulled the color from the workshop homepage (highlighted nav item) in case that's of use to @hannahkane and @xmatthewx.

**Comment by chadsansing** [comment]
![mcw-title-slide](https://cloud.githubusercontent.com/assets/4128600/14393755/89c6a19c-fd96-11e5-808a-34ad7f642d17.png)

**Comment by verenanz1** [comment]
Love :)

**Comment by xmatthewx** [comment]
@chadsansing – feel free to bring this and other projects to our design crit on Wednesday. The team would be glad to give feedback and help make sure colors and type stay aligned across our programs. It's currently scheduled for 3:30 ET, but will likely to shift to 1:30 ET starting next week.

**Comment by chadsansing** [comment]
Hoping to use this for the 4/12 curriculum workshop webcast, but can hold off if necessary, @xmatthewx. This week looks booked, but will try to make a future crit session if that's best.

**Comment by xmatthewx** [comment]
@chadsansing – I don't want to block you, but we'll need a little time to put together the style guide. It's possible that a project will wrap up early this heartbeat and a designer can jump in to lend a hand. Or we can rely on crit or the next heartbeat to handle this. cc @hannahkane

**Comment by hannahkane** [comment]
just clarifying, @xmatthewx - can the workshop team use the graphic as is for the April 12th webcast, and then we can triage and potentially provide additional design support for future episodes?

**Comment by chadsansing** [comment]
@xmatthewx, @hannahkane - no rush. We are going to punt for this episode and work on setting up the graphic and music for the May 10th episode. We'll put the grapic through a proper design crit in the interim.

**Comment by emmairwin** [comment]
Closing for now.
